[package]
name = "proc-macro-crate"
version = "2.0.1"
description = "Patches proc-macro-crate 2 to 3"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/patches/proc-macro-crate"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = []
edition = "2021"
rust-version = "1.66"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
proc-macro-crate = "3"
