[workspace]
resolver = "2"

members = [
        "common",
        "consensus",
        "cryptonight",
        "random-x",
	#"cuprate",
    #    "database",
        "net/levin",
        "net/monero-wire",
     #   "p2p",
      #  "p2p/sync-states"
]
