[package]
name = "frost"
version = "0.1.0"
description = "Implementation of FROST over ff/group"
license = "MIT"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"

[dependencies]
thiserror = "1"

rand_core = "0.6"
hex = "0.4"

sha2 = { version = "0.10", optional = true }

ff = "0.12"
group = "0.12"

elliptic-curve = { version = "0.12", features = ["hash2curve"], optional = true }
p256 = { version = "0.11", features = ["arithmetic", "hash2curve"], optional = true }
k256 = { version = "0.11", features = ["arithmetic", "hash2curve"], optional = true }
dalek-ff-group = { path = "../dalek-ff-group", optional = true }

transcript = { path = "../transcript" }

multiexp = { path = "../multiexp", features = ["batch"] }

[dev-dependencies]
rand = "0.8"

sha2 = "0.10"
elliptic-curve = { version = "0.12", features = ["hash2curve"] }
p256 = { version = "0.11", features = ["arithmetic", "hash2curve"] }

[features]
curves = []
kp256 = ["elliptic-curve"]
p256 = ["curves", "kp256", "sha2", "dep:p256"]
k256 = ["curves", "kp256", "sha2", "dep:k256"]
ed25519 = ["curves", "sha2", "dalek-ff-group"]
