[package]
name = "frost"
version = "0.1.0"
description = "Implementation of FROST over ff/group"
license = "MIT"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"

[dependencies]
thiserror = "1"

rand_core = "0.6"

ff = "0.11"
group = "0.11"

blake2 = "0.10"
transcript = { path = "../transcript" }

[dev-dependencies]
rand = "0.8"
sha2 = "0.10"
k256 = { version = "0.10", features = ["arithmetic"] }
