[package]
name = "serai-processor"
version = "0.1.0"
description = "Multichain processor premised on canonicity to reach distributed consensus automatically"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = []
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1"
rand_core = "0.6"
thiserror = "1"

group = "0.12"

transcript = { package = "flexible-transcript", path = "../crypto/transcript", features = ["recommended"] }
frost = { package = "modular-frost", path = "../crypto/frost", features = ["secp256k1", "ed25519"] }

serai-coin = { path = "../coin" }

[dev-dependencies]
hex = "0.4"

futures = "0.3"
tokio = { version = "1", features = ["full"] }

serai-coin = { path = "../coin", features = ["test"] }
