[package]
name = "serai-processor"
version = "0.1.0"
description = "Multichain processor premised on canonicity to reach distributed consensus automatically"
license = "AGPL-3.0-only"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"

[dependencies]
async-trait = "0.1"
rand_core = "0.6"
thiserror = "1"

curve25519-dalek = { version = "3", features = ["std"] }
blake2 = "0.10"

transcript = { path = "../crypto/transcript" }
dalek-ff-group = { path = "../crypto/dalek-ff-group" }
frost = { path = "../crypto/frost" }

monero = { version = "0.16", features = ["experimental"] }
monero-serai = { path = "../coins/monero", features = ["multisig"] }

[dev-dependencies]
rand = "0.8"
tokio = { version = "1", features = ["full"] }
