[package]
name = "monero-wire"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Boog900"]
repository = "https://github.com/SyntheticBird45/cuprate/tree/main/net/monero-wire"


[dependencies]
levin-cuprate = {path="../levin"}
monero-epee-bin-serde = { workspace = true, features = ["container_as_blob"] }
serde = { workspace = true, features = ["derive", "std"]}
serde_bytes = { workspace = true, features = ["std"]}
thiserror = { workspace = true }

[dev-dependencies]
hex = { workspace = true, features = ["std"]}

