[package]
name = "monero-wire"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Boog900"]
repository = "https://github.com/SyntheticBird45/cuprate/tree/main/net/monero-wire"


[dependencies]
levin-cuprate = {path="../levin"}
epee-encoding = { git = "https://github.com/boog900/epee-encoding"}
monero-epee-bin-serde = {git = "https://github.com/monero-rs/monero-epee-bin-serde.git"}
serde = {version = "1", features = ["derive"]}

[dev-dependencies]
hex = "0.4.3"

