[package]
name = "cuprate-test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
monero-wire = {path = "../net/monero-wire"}
monero-p2p = {path = "../p2p/monero-p2p" }

futures = "0.3.29"
async-trait = "0.1.74"

borsh = {version = "1.2.1", features = ["derive"]}