[package]
name = "flexible-transcript"
version = "0.3.1"
description = "A simple transcript trait definition, along with viable options"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/crypto/transcript"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["transcript"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
rustversion = "1"

subtle = { version = "^2.4", default-features = false }
zeroize = { version = "^1.5", default-features = false }

digest = { version = "0.10", default-features = false, features = ["core-api"] }

blake2 = { version = "0.10", default-features = false, optional = true }
merlin = { version = "3", default-features = false, optional = true }

[dev-dependencies]
sha2 = { version = "0.10", default-features = false }
blake2 = { version = "0.10", default-features = false }

[features]
recommended = ["blake2"]
merlin = ["dep:merlin"]
tests = []
