[package]
name = "transcript"
version = "0.1.0"
description = "A simple transcript definition"
license = "MIT"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"

[dependencies]
rand_core = "0.6"
rand_chacha = "0.3"

digest = "0.10"

merlin = { version = "3", optional = true }

[features]
merlin = ["dep:merlin"]
