[package]
name = "transcript-trait"
version = "0.1.0"
description = "A simple transcript trait definition"
license = "MIT"
repository = "https://github.com/serai-dex/serai"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["transcript"]
edition = "2021"

[dependencies]
digest = "0.10"

merlin = { version = "3", optional = true }

[features]
merlin = ["dep:merlin"]
