[package]
name = "coordinator"
version = "0.1.0"
description = "Serai coordinator to prepare batches and sign transactions"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/coordinator"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = []
edition = "2021"
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
log = "0.4"

blake2 = "0.10"

frost = { package = "modular-frost", path = "../crypto/frost" }

serai-db = { path = "../common/db" }

processor-messages = { package = "processor-messages", path = "../processor/messages" }
tributary = { package = "tributary-chain", path = "./tributary" }

serai-client = { path = "../substrate/client", features = ["serai"] }

tokio = { version = "1", features = ["full"] }

[dev-dependencies]
rand_core = "0.6"

tributary = { package = "tributary-chain", path = "./tributary", features = ["tests"] }
