[package]
name = "coordinator"
version = "0.1.0"
description = "Serai coordinator to prepare batches and sign transactions"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/coordinator"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = []
edition = "2021"
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
async-trait = "0.1"

zeroize = "^1.5"

blake2 = "0.10"

transcript = { package = "flexible-transcript", path = "../crypto/transcript", features = ["recommended"] }
ciphersuite = { path = "../crypto/ciphersuite" }
frost = { package = "modular-frost", path = "../crypto/frost" }

scale = { package = "parity-scale-codec", version = "3", features = ["derive"] }

sp-application-crypto = { git = "https://github.com/serai-dex/substrate", default-features = false }

serai-db = { path = "../common/db" }

processor-messages = { package = "processor-messages", path = "../processor/messages" }
tributary = { package = "tributary-chain", path = "./tributary" }

serai-client = { path = "../substrate/client", features = ["serai"] }

log = "0.4"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
rand_core = "0.6"

tributary = { package = "tributary-chain", path = "./tributary", features = ["tests"] }
