[package]
name = "monero-p2p"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Boog900"]

[features]
default = ["borsh"]
borsh = ["dep:borsh"]

[dependencies]
monero-wire = {path= "../../net/monero-wire"}
cuprate-common = {path = "../../common", features = ["borsh"]}

tokio = { workspace = true, features = ["net", "sync", "macros"]}
tokio-util = { workspace = true, features = ["codec"] }
tokio-stream = { workspace = true, features = ["sync"]}
futures = { workspace = true, features = ["std", "async-await"] }
async-trait = { workspace = true }
tower = { workspace = true, features = ["util"] }

thiserror = { workspace = true }
tracing = { workspace = true, features = ["std"] }

borsh = { workspace = true, default-features = false, features = ["derive", "std"], optional = true }

[dev-dependencies]
cuprate-test-utils = {path = "../../test-utils"}

hex = { workspace = true }
tokio = { workspace = true, features = ["net", "rt-multi-thread", "rt", "macros"]}
tracing-subscriber = { workspace = true }
