[package]
name = "monero-address-book"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Boog900"]


[dependencies]
cuprate-common = {path = "../../common"}
monero-wire = {path= "../../net/monero-wire"}
monero-p2p = {path = "../monero-p2p" }

tower = { version= "0.4.13", features = ["util", "buffer"] }
tokio = {version = "1.34.0", default-features = false, features = ["time", "fs", "rt"]}

futures = "0.3.29"
pin-project = "1.1.3"
async-trait = "0.1.74"

thiserror = "1.0.50"
tracing = "0.1.40"

rand = "0.8.5"

borsh = {version = "1.2.1", features = ["derive"]}

[dev-dependencies]
tokio = {version = "1.34.0", features = ["rt-multi-thread", "macros"]}
cuprate-test-utils = {path = "../../test-utils"}
