[package]
name = "monero-consensus"
version = "0.1.0"
edition = "2021"
description = "A crate implimenting all Moneros consensus rules."
license = "MIT"
authors = ["Boog900"]
repository = "https://github.com/Cuprate/cuprate/tree/main/consensus"

[features]
default = ["binaries"]
binaries = [
    "tokio/rt-multi-thread",
    "tokio/macros",
    "dep:tracing-subscriber",
    "tower/retry",
    "tower/balance",
    "tower/buffer",
    "tower/timeout",
    "dep:serde_json",
    "dep:serde",
    "dep:monero-epee-bin-serde",
    "dep:monero-wire"
]

[dependencies]
hex = "0.4"
thiserror = "1"
tower = {version = "0.4", features = ["util"]}
tracing = "0.1"
futures = "0.3"

crypto-bigint = "0.5"
curve25519-dalek = "4"

randomx-rs = "1"
monero-serai = {git="https://github.com/Cuprate/serai.git", rev = "39eafae"}
multiexp = {git="https://github.com/Cuprate/serai.git", rev = "39eafae"}
dalek-ff-group = {git="https://github.com/Cuprate/serai.git", rev = "39eafae"}

cuprate-common = {path = "../common"}
cryptonight-cuprate = {path = "../cryptonight"}

rayon = "1"
tokio = "1"

# used in binaries
monero-wire = {path="../net/monero-wire", optional = true}
monero-epee-bin-serde = {git = "https://github.com/monero-rs/monero-epee-bin-serde.git", rev = "e4a585a", optional = true}
serde_json = {version = "1", optional = true}
serde = {version = "1", optional = true, features = ["derive"]}
tracing-subscriber = {version = "0.3", optional = true}
# here to help cargo to pick a version - remove me
syn = "2.0.37"

[profile.dev]
opt-level = 3
