[package]
name = "multiexp"
version = "0.1.0"
description = "Multiexponentation algorithms for ff/group"
license = "MIT"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"

[dependencies]
group = "0.12"

rand_core = { version = "0.6", optional = true }

[features]
batch = ["rand_core"]
