[package]
name = "multiexp"
version = "0.3.1"
description = "Multiexponentation algorithms for ff/group"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/crypto/multiexp"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["multiexp", "ff", "group"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
rustversion = "1"

zeroize = { version = "^1.5", features = ["zeroize_derive"] }

ff = "0.13"
group = "0.13"

rand_core = { version = "0.6", optional = true }

[dev-dependencies]
rand_core = "0.6"

k256 = { version = "^0.13.1", default-features = false, features = ["std", "arithmetic", "bits"] }
dalek-ff-group = { path = "../dalek-ff-group" }

[features]
batch = ["rand_core"]
