[package]
name = "monero-serai"
version = "0.1.0"
description = "Implementation of Monero transaction signing in Rust"
license = "MIT"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"

[dependencies]
lazy_static = "1"
thiserror = "1"

rand_core = "0.6"
rand_chacha = { version = "0.3", optional = true }

tiny-keccak = { version = "2.0", features = ["keccak"] }
blake2 = "0.10"

curve25519-dalek = { version = "3.2", features = ["std", "simd_backend"] }

ff = { version = "0.11", optional = true }
group = { version = "0.11", optional = true }
dalek-ff-group = { path = "../../sign/dalek-ff-group", optional = true }
frost = { path = "../../sign/frost", optional = true }

# Locked to this specific patch version due to a bug we compensate for
monero = { version = "0.16.0", features = ["experimental"] }

hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
monero-epee-bin-serde = "1.0"
reqwest = { version = "0.11", features = ["json"] }

[features]
multisig = ["ff", "group", "dalek-ff-group", "frost", "rand_chacha"]

[dev-dependencies]
rand = "0.8"

tokio = { version = "1.17.0", features = ["full"] }
