const listUrl = "https://publicsuffix.org/list/public_suffix_list.dat";
const outPath = new URL("./public-suffix-list.ts", import.meta.url);

const response = await fetch(listUrl);
if (!response.ok) {
  throw new Error(`download failed: ${response.status}`);
}

const rules: string[] = [];
for (const raw of (await response.text()).split(/\r?\n/)) {
  const line = raw.trim();
  if (!line || line.startsWith("//")) continue;
  if (line.includes("===BEGIN")) continue;
  rules.push(line);
}

const body = rules.map((rule) => `  ${JSON.stringify(rule)},`).join("\n");
const source = `// generated by download-public-suffix.ts\nexport const publicSuffixRules = [\n${body}\n] as const;\n`;

await Bun.write(outPath, source);
console.log(`${rules.length} rules -> ${outPath.pathname}`);
