name: Message Queue Tests

on:
  push:
    branches:
      - develop
    paths:
      - "message-queue/**"
      - "tests/message-queue/**"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Build Dependencies
        uses: ./.github/actions/build-dependencies
        with:
          github-token: ${{ inputs.github-token }}

      - name: Run message-queue Docker tests
        run: cd tests/message-queue && cargo test
