name: Processor Tests

on:
  push:
    branches:
      - develop
    paths:
      - "processor/**"
      - "tests/docker/**"
      - "tests/processor/**"

  pull_request:
    paths:
      - "processor/**"
      - "tests/docker/**"
      - "tests/processor/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Build Dependencies
        uses: ./.github/actions/build-dependencies
        with:
          github-token: ${{ inputs.github-token }}

      - name: Run processor Docker tests
        run: cd tests/processor && cargo test
