name: Tests

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  test-common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: |
          GITHUB_CI=true cargo test --all-features \
            -p std-shims \
            -p zalloc \
            -p serai-db

  test-crypto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: |
          GITHUB_CI=true cargo test --all-features \
            -p flexible-transcript \
            -p ff-group-tests \
            -p dalek-ff-group \
            -p minimal-ed448 \
            -p ciphersuite \
            -p multiexp \
            -p schnorr-signatures \
            -p dleq \
            -p dkg \
            -p modular-frost \
            -p frost-schnorrkel

  test-coins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: |
          GITHUB_CI=true cargo test --all-features \
            -p bitcoin-serai \
            -p ethereum-serai \
            -p monero-generators \
            -p monero-serai

  test-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: |
          GITHUB_CI=true cargo test --all-features \
            -p serai-message-queue \
            -p serai-processor-messages \
            -p serai-processor \
            -p tendermint-machine \
            -p tributary-chain \
            -p serai-coordinator

  test-substrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: |
          GITHUB_CI=true cargo test --all-features \
            -p serai-primitives \
            -p serai-tokens-primitives \
            -p serai-tokens-pallet \
            -p serai-in-instructions-primitives \
            -p serai-in-instructions-pallet \
            -p serai-validator-sets-primitives \
            -p serai-validator-sets-pallet \
            -p serai-runtime \
            -p serai-node

  test-serai-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build node
        run: |
          cd substrate/node
          cargo build

      - name: Run Tests
        run: GITHUB_CI=true cargo test --all-features -p serai-client
